### ISSUE TITLE
Invalid manifest

### ISSUE THREAD

**Issue by ackstorm23** [brockgr/chrometile#2]
There was a problem with the download. Please contact the developer or try again later.

Experienced at https://chrome.google.com/webstore/detail/tiling-window-manager-for/aikaaejchodabfpkipfonnekofgepakh

**Comment by brockgr** [comment]
Should be fixed by b994c2a6a9ac18aad1b07e949628deb39b26f892 in version 0.5

Should propagate from CWS soon.
